### ISSUE TITLE
new matchrequest table doesnt save value correctly (opponent and status)

### ISSUE THREAD

**Issue by nanonano7** [nanonano7/eoschess#4]
cpp
https://github.com/nanonano7/eoschess/blob/e04d8144b2ecee12053952aa749c6bfbe74c0f74/chess.cpp#L252-L260
abi
https://github.com/nanonano7/eoschess/blob/e04d8144b2ecee12053952aa749c6bfbe74c0f74/chess.abi#L69-L79
hpp
https://github.com/nanonano7/eoschess/blob/e04d8144b2ecee12053952aa749c6bfbe74c0f74/chess.hpp#L30-L38
eosc output
```
{
      "requestid": 1512804337,
      "matchid": 1512804337,
      "status": 0,
      "opponent": ".5uhv4w",
      "opponentside": 0,
      "maxmoveinterval": 10000,
      "matchstart": 1
    }
```

**Comment by SheldonHH** [comment]
It may because the problem of `uint_8_t` may try to change to other uint32_t
![](https://user-images.githubusercontent.com/16319106/33793785-23b36cf2-dcf9-11e7-890d-da644bef6953.png)
