### ISSUE TITLE
How should I migrate ERC 20 token accounts and balances to EOS ?

### ISSUE THREAD

**Issue by sivachaitanya** [nanonano7/eoschess#9]
Hi Nano,

I remember you as the very active person and core developer from EOS Telegram group, Sorry but I am not looking to spam your Issue feed here but just trying to check if you have solution for my ever burning problem. Lets lets example for EOS, they had successful token sale on ERC-20 on Ethereum mainnet, my question is how are they going to map the ERC20 tokens to EOS balances ? Can you please explain me breifly ?

Cheers

**Comment by nanonano7** [comment]
this [tool](https://github.com/EOSIO/genesis) will be used to take a snapshot at the of the distribution that will be put in the genesis block of the mainnet. The users that have their keys registered will be able to claim their balances with it.
